javac -cp ..\lib\*;c:\tomcat9\lib\*;. com\thinking\machines\drone\common\*.java
javac -cp ..\lib\*;c:\tomcat9\lib\*;. com\thinking\machines\drone\common\request\*.java
javac -cp ..\lib\*;c:\tomcat9\lib\*;. com\thinking\machines\drone\common\response\*.java
javac -cp ..\lib\*;c:\tomcat9\lib\*;. com\thinking\machines\drone\pojo\*.java
javac -cp ..\lib\*;c:\tomcat9\lib\*;. com\thinking\machines\connection\*.java
javac -cp ..\lib\*;c:\tomcat9\lib\*;. com\thinking\machines\user\*.java
javac -cp ..\lib\*;c:\tomcat9\lib\*;. com\thinking\machines\user\pojo\*.java
javac -classpath ..\lib\*;c:\tomcat9\lib\*;. ..\..\*.java
javac -cp ..\lib\*;c:\tomcat9\lib\*;. com\thinking\machines\cms\configuration\*.java
javac -cp ..\lib\*;c:\tomcat9\lib\*;. com\thinking\machines\cms\services\model\*.java
javac -cp ..\lib\*;c:\tomcat9\lib\*;. com\thinking\machines\cms\services\pojo\*.java
javac -cp ..\lib\*;c:\tomcat9\lib\*;. com\thinking\machines\cms\services\utility\*.java
javac -cp ..\lib\*;c:\tomcat9\lib\*;. com\thinking\machines\cms\services\*.java
javac -cp ..\lib\*;c:\tomcat9\lib\*;. com\thinking\machines\cms\*.java
javac -cp ..\lib\*;c:\tomcat9\lib\*;. *.java
